config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :registrations, only: [:new, :create]
  resources :logins, only: [:new, :create]
  resources :posts
  root 'posts#index'
  get 'logins/logout' => 'logins#logout', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post

  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Email or password is wrong"
      render :new, status: :unprocessable_entity
    end
  end

  def logout
    reset_session
    redirect_to :root
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
  end

  def index
    @posts = Post.all
    if session[:user_id] !=nil
      @user = User.find(session[:user_id])
    end
  end

  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @author = User.find(@post.user_id)
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(params.require(:post).permit(:title, :body))
        format.html { redirect_to @post, notice: 'The post has been updated' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @post = Post.new
    user = User.find(session[:user_id])
    params.require(:post).permit(:title, :body)
    post_params = params[:post]

    if user
      @post.title = post_params[:title]
      @post.body = post_params[:body]
      @post.user_id = user.id
      @post.save
    else
      flash[:notice] = "Unable to create post"
      render :new, status: :unprocessable_entity
    end

    if @post
      redirect_to post_path(@post.id)
    else
      flash[:notice] = "Unable to create post"
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>
    <% if session[:user_id] == nil %>
      <%= link_to "Log in", new_login_path %>
      <%= link_to "Register", new_registration_path %>
    <% else %>
      <%= link_to "Log out", logout_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
Log in

<%= form_with model: @user, url: logins_path do |form| %>
<%= form.label "Email" %>
  <%= form.text_field :email %>
  <%= form.label "Password" %>
  <%= form.password_field :password %>
  <%= form.submit "Log in" %>
<% end %>

<%= link_to "Registration", new_registration_path %>

app/views/posts/edit.html.erb
<% if @author.present? %>
Editing post
  <%= form_with model: @post do |f| %>
    <%= f.label "Title" %>
    <%= f.text_field :title %>
    <%= f.label "Body" %>
    <%= f.text_field :body %>
    <%= f.submit "Update post" %>
  <% end %>
<% else %>
  No permission to edit the post
<% end %>

app/views/posts/index.html.erb
<h2>Posts</h2>
<% if @user.present? %>
  <%= link_to "New post", new_post_path %>
<% end %>
<% for post in @posts do %>
  <p>
    Title: <%= post.title %><br />
    Body: <%= post.body %><br />
    Author: <%= post.user.email %><br />
  </p>
  <%= link_to "View post", post_path(post) %>
  <% if @user.present? && @user.id == post.user_id %>
    <%= link_to "Edit post", edit_post_url(post) %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
New post

<%= form_with model: @post do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.label "Body" %>
  <%= f.text_field :body %>
  <%= f.submit "Create post" %>
<% end %>

app/views/posts/show.html.erb
Post

<%= @post.title %>
<%= @post.body %>